<?php

use Illuminate\Database\Seeder;

class realUserDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_details')->delete();
        
        \DB::table('user_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 3,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-02 21:10:47',
                'updated_at' => '2020-06-02 21:10:47',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 4,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-02 21:11:31',
                'updated_at' => '2020-06-02 21:11:31',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 5,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-02 21:13:20',
                'updated_at' => '2020-06-02 21:13:20',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 6,
                'language_id' => 3,
                'email' => 'raghav.dhingra15@gmail.com',
                'firstname' => 'Raghav',
                'lastname' => 'Dhingra',
                'college' => 'IPU',
                'city' => 'Panipat',
                'gpa' => '10.00',
                'country_id' => 100,
                'discipline_id' => 1,
                'qualification_id' => 5,
                'created_at' => '2020-06-03 08:12:03',
                'updated_at' => '2020-06-18 21:10:26',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 7,
                'language_id' => 3,
                'email' => 'justabouttech15@gmail.com',
                'firstname' => 'JUST ABOUT',
                'lastname' => 'TECH',
                'college' => '897',
                'city' => '89',
                'gpa' => '8.00',
                'country_id' => 100,
                'discipline_id' => 1,
                'qualification_id' => 1,
                'created_at' => '2020-06-03 08:14:26',
                'updated_at' => '2020-06-03 08:14:56',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 9,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-06 15:17:02',
                'updated_at' => '2020-06-06 15:17:02',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 8,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-10 07:15:25',
                'updated_at' => '2020-06-10 07:15:25',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 10,
                'language_id' => 3,
                'email' => 'chetan.kashyap7497@gmail.com',
                'firstname' => 'Chetan',
                'lastname' => 'Kashyap',
                'college' => 'Delhi University',
                'city' => 'New Delhi',
                'gpa' => '8.00',
                'country_id' => 100,
                'discipline_id' => 3,
                'qualification_id' => 4,
                'created_at' => '2020-06-10 10:22:55',
                'updated_at' => '2020-06-10 10:25:11',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 11,
                'language_id' => 6,
                'email' => 'maurya.rahul111@gmail.com',
                'firstname' => 'Rahul',
                'lastname' => 'Maurya',
                'college' => 'DU',
                'city' => 'New Delhi',
                'gpa' => '7.00',
                'country_id' => 100,
                'discipline_id' => 5,
                'qualification_id' => 1,
                'created_at' => '2020-06-10 20:04:43',
                'updated_at' => '2020-06-10 21:15:09',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 12,
                'language_id' => 3,
                'email' => 'maninderstar1998@gmail.com',
                'firstname' => 'Maninder',
                'lastname' => 'singh',
                'college' => 'GTBIT',
                'city' => 'Delhi',
                'gpa' => '8.20',
                'country_id' => 100,
                'discipline_id' => 1,
                'qualification_id' => 4,
                'created_at' => '2020-06-10 22:30:12',
                'updated_at' => '2020-06-10 22:30:46',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 13,
                'language_id' => 7,
                'email' => 'elsya.angkawati@gmail.com',
                'firstname' => 'elsya',
                'lastname' => 'angkawati',
                'college' => 'Ancol',
                'city' => 'Jakarta',
                'gpa' => '0.00',
                'country_id' => 101,
                'discipline_id' => 1,
                'qualification_id' => 5,
                'created_at' => '2020-06-11 09:12:22',
                'updated_at' => '2020-06-11 09:13:32',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 14,
                'language_id' => 7,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-11 09:15:35',
                'updated_at' => '2020-06-11 09:15:35',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 22,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-13 12:46:10',
                'updated_at' => '2020-06-13 12:46:10',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 23,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-14 08:51:04',
                'updated_at' => '2020-06-14 08:51:04',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 24,
                'language_id' => 6,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-14 13:26:13',
                'updated_at' => '2020-06-14 13:26:13',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 25,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-14 18:59:09',
                'updated_at' => '2020-06-14 18:59:09',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 26,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-14 19:01:45',
                'updated_at' => '2020-06-14 19:01:45',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 16,
                'language_id' => 3,
                'email' => 'krishankirti9@gmail.com',
                'firstname' => 'Kirti',
                'lastname' => 'Krishan',
                'college' => 'Peking University',
                'city' => 'Shenzhen',
                'gpa' => '3.20',
                'country_id' => 45,
                'discipline_id' => 3,
                'qualification_id' => 3,
                'created_at' => '2020-06-16 17:53:57',
                'updated_at' => '2020-06-16 17:54:32',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 27,
                'language_id' => 3,
                'email' => NULL,
                'firstname' => NULL,
                'lastname' => NULL,
                'college' => NULL,
                'city' => NULL,
                'gpa' => NULL,
                'country_id' => NULL,
                'discipline_id' => NULL,
                'qualification_id' => NULL,
                'created_at' => '2020-06-16 20:20:41',
                'updated_at' => '2020-06-16 20:20:41',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 28,
                'language_id' => 5,
                'email' => 'yasminaziz2004@gmail.com',
                'firstname' => 'Jennie',
                'lastname' => 'Student',
                'college' => 'Tazi High School',
                'city' => 'Casablanca',
                'gpa' => '3.00',
                'country_id' => 146,
                'discipline_id' => 5,
                'qualification_id' => 5,
                'created_at' => '2020-06-16 20:44:59',
                'updated_at' => '2020-06-16 20:47:03',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 30,
                'language_id' => 3,
                'email' => 'rojasfernanda201@gmail.com',
                'firstname' => 'fernanda',
                'lastname' => 'rojas',
                'college' => 'Japanese Paraguayan School',
                'city' => 'asunción',
                'gpa' => '5.00',
                'country_id' => 168,
                'discipline_id' => 5,
                'qualification_id' => 5,
                'created_at' => '2020-06-18 18:58:51',
                'updated_at' => '2020-06-18 19:01:55',
            ),
        ));
        
        
    }
}